// Code generated by protoc-gen-go. DO NOT EDIT.
// source: brief.proto

package protogrpcuser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserBrief struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBrief) Reset()         { *m = UserBrief{} }
func (m *UserBrief) String() string { return proto.CompactTextString(m) }
func (*UserBrief) ProtoMessage()    {}
func (*UserBrief) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec727588a29b67f7, []int{0}
}

func (m *UserBrief) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBrief.Unmarshal(m, b)
}
func (m *UserBrief) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBrief.Marshal(b, m, deterministic)
}
func (m *UserBrief) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBrief.Merge(m, src)
}
func (m *UserBrief) XXX_Size() int {
	return xxx_messageInfo_UserBrief.Size(m)
}
func (m *UserBrief) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBrief.DiscardUnknown(m)
}

var xxx_messageInfo_UserBrief proto.InternalMessageInfo

func (m *UserBrief) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserBrief) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*UserBrief)(nil), "brief.UserBrief")
}

func init() {
	proto.RegisterFile("brief.proto", fileDescriptor_ec727588a29b67f7)
}

var fileDescriptor_ec727588a29b67f7 = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2a, 0xca, 0x4c,
	0x4d, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xf4, 0xb9, 0x38, 0x43,
	0x8b, 0x53, 0x8b, 0x9c, 0x40, 0x1c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x20, 0x4b, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09, 0x2c,
	0x02, 0x66, 0x3b, 0xf1, 0x47, 0xf1, 0x82, 0x0d, 0x48, 0x2f, 0x2a, 0x48, 0x2e, 0x05, 0xea, 0x4c,
	0x62, 0x03, 0x73, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x1d, 0xbd, 0xb9, 0x5e, 0x00,
	0x00, 0x00,
}
