// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protogrpcuser

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBriefByIDsRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBriefByIDsRequest) Reset()         { *m = GetBriefByIDsRequest{} }
func (m *GetBriefByIDsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBriefByIDsRequest) ProtoMessage()    {}
func (*GetBriefByIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetBriefByIDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBriefByIDsRequest.Unmarshal(m, b)
}
func (m *GetBriefByIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBriefByIDsRequest.Marshal(b, m, deterministic)
}
func (m *GetBriefByIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBriefByIDsRequest.Merge(m, src)
}
func (m *GetBriefByIDsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBriefByIDsRequest.Size(m)
}
func (m *GetBriefByIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBriefByIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBriefByIDsRequest proto.InternalMessageInfo

func (m *GetBriefByIDsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetBriefByIDsResponse struct {
	Users                []*UserBrief `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetBriefByIDsResponse) Reset()         { *m = GetBriefByIDsResponse{} }
func (m *GetBriefByIDsResponse) String() string { return proto.CompactTextString(m) }
func (*GetBriefByIDsResponse) ProtoMessage()    {}
func (*GetBriefByIDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetBriefByIDsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBriefByIDsResponse.Unmarshal(m, b)
}
func (m *GetBriefByIDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBriefByIDsResponse.Marshal(b, m, deterministic)
}
func (m *GetBriefByIDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBriefByIDsResponse.Merge(m, src)
}
func (m *GetBriefByIDsResponse) XXX_Size() int {
	return xxx_messageInfo_GetBriefByIDsResponse.Size(m)
}
func (m *GetBriefByIDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBriefByIDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBriefByIDsResponse proto.InternalMessageInfo

func (m *GetBriefByIDsResponse) GetUsers() []*UserBrief {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*GetBriefByIDsRequest)(nil), "user.GetBriefByIDsRequest")
	proto.RegisterType((*GetBriefByIDsResponse)(nil), "user.GetBriefByIDsResponse")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0xb8, 0x93, 0x8a, 0x32, 0x53,
	0xd3, 0x20, 0x42, 0x4a, 0x1a, 0x5c, 0x22, 0xee, 0xa9, 0x25, 0x4e, 0x20, 0x11, 0xa7, 0x4a, 0x4f,
	0x97, 0xe2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x01, 0x2e, 0xe6, 0xcc, 0x94, 0x62,
	0x09, 0x46, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x10, 0x53, 0xc9, 0x9e, 0x4b, 0x14, 0x4d, 0x65, 0x71,
	0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x1a, 0x17, 0x2b, 0xc8, 0x5c, 0x88, 0x62, 0x6e, 0x23, 0x01,
	0x3d, 0x88, 0xf9, 0xa1, 0x40, 0x31, 0xb0, 0xea, 0x20, 0x88, 0xb4, 0x51, 0x10, 0x17, 0x0b, 0x48,
	0x4c, 0xc8, 0x8b, 0x8b, 0x17, 0xc5, 0x20, 0x21, 0x29, 0x3d, 0xb0, 0x1b, 0xb1, 0xb9, 0x43, 0x4a,
	0x1a, 0xab, 0x1c, 0xc4, 0x66, 0x25, 0x06, 0x27, 0xfe, 0x28, 0x5e, 0xb0, 0x3f, 0xd2, 0x8b, 0x0a,
	0x92, 0x41, 0x0a, 0x93, 0xd8, 0xc0, 0x5c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x04,
	0x38, 0xb0, 0xf7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	// Get brief data of array brands
	GetBriefByIDs(ctx context.Context, in *GetBriefByIDsRequest, opts ...grpc.CallOption) (*GetBriefByIDsResponse, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetBriefByIDs(ctx context.Context, in *GetBriefByIDsRequest, opts ...grpc.CallOption) (*GetBriefByIDsResponse, error) {
	out := new(GetBriefByIDsResponse)
	err := c.cc.Invoke(ctx, "/user.User/GetBriefByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	// Get brief data of array brands
	GetBriefByIDs(context.Context, *GetBriefByIDsRequest) (*GetBriefByIDsResponse, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) GetBriefByIDs(ctx context.Context, req *GetBriefByIDsRequest) (*GetBriefByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBriefByIDs not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetBriefByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBriefByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetBriefByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetBriefByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetBriefByIDs(ctx, req.(*GetBriefByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBriefByIDs",
			Handler:    _User_GetBriefByIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
